### ISSUE TITLE
No image at path clipboardImage1.png

### ISSUE THREAD

**Issue by superficialt** [Timag/imageclipr#1] opened 2019-08-29 09:33 UTC
Hi,

I think this is a great idea, was really excited to find that it exists.  However, it doesn't seem to work for me. Perhaps I have installed it incorrectly.

I used:
packages.install('devtools')
devtools::install_github('Timag/imageclipr')

This didn't work at all - threw an error message complaining that PIL wasn't installed. So from Terminal I ran 'sudo pip install pillow'.  

Now when I run 'devtools::install_github('Timag/imageclipr')' it installs without error but when I try to paste something in I get this error: 
![image](https://user-images.githubusercontent.com/46779095/63928781-1fb62e80-ca48-11e9-88f0-013ee330e833.png)

MacBook Pro 2018 running OS X Mojave 10.14.6
RStudio 1.1.456
I have Python installed, I think, on this machine but I have never used it. This may be the issue - I have no idea whether it's working, whether all the paths are correct etc. 

Any suggestions?

**Comment by Toniiiio** [comment] 2019-08-29 15:06
Hi @superficialt ,

thanks for your feedback. I didnt have the chance to test the package on Mac, a friend wanted to do that, but didnt find the time. So i cant reproduce it at the moment :(.

I made an update to the code. Could you re-install the latest (dev) version from github and see if there comes an error message- If that doesnt help - could you check if there was a file created in the same directory as your notebook file is?

If that doesnt help i will try to get my hands on a mac.

Best regards,
Tonio

**Comment by superficialt** [comment] 2019-08-29 19:42
Thanks for the input. I've updated the package, and restarted R. It seems to be more broken now I'm afraid. I get an error message now before the code clip (in my image above) appears:

`Error in value[[3L]](cond) : 
  Error copying the file with python. Error message reads: Error in py_run_string_impl(code, local, convert): Evaluation error: option error has NULL value.
In addition: Warning messages:
1: replacing previous import ‘shiny::runExample’ by ‘shinyjs::runExample’ when loading ‘imageclipr’ 
2: In if ("AttributeError: 'NoneType' object has no attribute 'save'" ==  :
  the condition has length > 1 and only the first element will be used`

**Comment by Toniiiio** [comment] 2019-08-31 15:11
Not more broken, more detailed logging :) The python code seems to fail. Checking the error leads to: https://github.com/rstudio/reticulate/issues/494. 
So it could be a bug in rstudio.

Could you have a look at it and check if the error occurs if you work outside a project or update rstudio to the referenced version?

**Comment by Toniiiio** [comment] 2019-09-04 21:22
any update @superficialt ?

**Comment by superficialt** [comment] 2019-09-06 09:31
Hi, 
Sorry I didn’t really understand the previous email. What is the referenced version?

Tom

**Comment by Toniiiio** [comment] 2019-09-06 16:44
I meant you could check: rstudio/reticulate#494. There they write about the same error message.
--> Action would be: 

- test code outside an rstudio project in case you are using one
- update rstudio to the version mentioned in rstudio/reticulate#494

**Comment by chlee-tabin** [comment] 2019-10-30 20:57
Hi,

I hit upon this repository, but I have the same error in Mac OSX, with almost the same error I guess (I have updated the RStudio to 1.2.5001.). Would you mind helping me to fix this? I was longing to have this feature for long time, and I really hope that I can share the use of the invented wheel!!

```
function (ImgfileName) 
paste0("![Plot title. ](", ImgfileName, ")")
<bytecode: 0x7fc6389d16b0>
<environment: namespace:imageclipr>
Error in value[[3L]](cond) : 
  Error copying the file with python. Error message reads: Error in py_run_string_impl(code, local, convert): AttributeError: 'NoneType' object has no attribute 'save'

Detailed traceback: 
  File "<string>", line 1, in <module>

In addition: Warning message:
In if ("AttributeError: 'NoneType' object has no attribute 'save'" ==  :
  the condition has length > 1 and only the first element will be used
```

![image](https://user-images.githubusercontent.com/31305155/67898235-4f5fe080-fb36-11e9-9c16-de2a79924a75.png)

**Comment by chlee-tabin** [comment] 2019-10-30 21:00
JFYI, I tested in python that ImageGrab.grabclipboard() worked...

**Comment by chlee-tabin** [comment] 2019-10-30 21:15
I think I found the error for Mac OSX.

It looks like that the filePath from the rstudioapi is throwing a path name that has tilda (~) as the home directory. And whenever that path is given to the python code, it fails.

**Comment by chlee-tabin** [comment] 2019-10-30 21:30
I created a pull request (although, I think due to this Windows Mac OSX differences in line breaks it shows a entire code changes) that fixes the issue and works with Mac OSX. (It is just one additional line, which I believe will not affect Windows usage).

**Comment by superficialt** [comment] 2019-10-31 10:01
OK, forgive my ignorance but how do I update to your version?

**Comment by Toniiiio** [comment] 2019-10-31 10:44
Thanks for the PR @chlee-tabin. You are right on the "diff" he showed me -168 + 170 lines of code, but thats fine. I merged the PR, thanks for the OSX support!

@superficialt. You can update now, by downloading the current version.

**Comment by chlee-tabin** [comment] 2019-11-11 20:28
@Timag Hi thanks again for the wonderful package which I am using it. I created one more pull request which I am happy if you decline, but I think it makes sense of naming the png files alongside the markdown file (I have multiple markdown files in a directory so makes it easier to pinpoint which images I pasted).

**Comment by Toniiiio** [comment] 2019-11-11 20:42
Sure, thanks for your contribution!!

**Closed as completed by Toniiiio** 2019-11-11 20:42 UTC
